import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/nav-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "YouTube",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./image/icon.png" sizes="32*32"/>
      </head>
      <body className={`${inter.className} bg-darkgray`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
